#!/usr/bin/env bash
set +e

. $TRAQ_PATH/traq_helper.sh

PROJECT="timestamps"
DATE=
WEEK=
MONTH=
YEAR=
while getopts ":p:d:w:m:y::v" opt "$@"
do
  case $opt in
    p)
      PROJECT="$OPTARG"
      ;;
    d)
      DATE="$OPTARG"
      ;;
    w)
      WEEK="$OPTARG"
      ;;
    m)
      MONTH="$OPTARG"
      ;;
    y)
      YEAR="$OPTARG"
      ;;
    \?)
      printf "Invalid option: -$OPTARG\n" >&2
      ;;
    :)
      printf "Option -$OPTARG requires an argument.\n" >&2
      exit 1
      ;;
  esac
done
shift $(($OPTIND - 1))

TAG=$1
shift
COMMENT=$@

if [ "$MONTH" == "" ]
then
  traq "$TAG" "$DATE" "$WEEK" "$PROJECT" "$COMMENT"
else
  # we default to the current year if not provided
  if [ "$YEAR" == "" ]
  then
    YEAR=$(date +"%Y")
  fi

  # properly calculate the last day in the provided month
  OFFSET_MONTH=$(echo "$MONTH + 1" | bc)
  OFFSET_YEAR=$YEAR
  if [ "$OFFSET_MONTH" -gt 12 ]
  then
    OFFSET_MONTH=1
    OFFSET_YEAR=$(echo "$YEAR + 1" | bc)
  fi
  last_day_in_month=$(date -v${OFFSET_YEAR}y -v${OFFSET_MONTH}m -v1d -v-1d +"%d")

  # execute traq for each date
  for i in $(seq 1 $last_day_in_month)
  do
    DAY_DATE=$(date -v${YEAR}y -v${MONTH}m -v${i}d +"%Y-%m-%d")
    traq "$TAG" "$DAY_DATE" "" "$PROJECT" ""
  done
fi