#!/usr/bin/env bash

set +e

. $TRAQ_PATH/traqtrans_helper.sh

TRAQ_CONTENT=""

# for i in ${!Array[@]}
# do
#   echo ${Array[i]}
# done

# tag_by_index[n] has its total stored in totalled_by_index[n]
tag_by_index=()
totalled_by_index=()

current_tag=""
started_at=""
ended_at=""

while read LINE
do
  if [ "$LINE" != "%%" ]
  then
    # sum up the timestamps
    timestamp=$(extract_date "$LINE")
    tag=$(extract_tag "$LINE")

    if [ "$timestamp" != "" -a "$tag" != "" ]
    then
      # first tag seen? just remember the tag
      if [ "$current_tag" = "" ]
      then
        current_tag="$tag"
        started_at="$timestamp"
        ended_at=""
      else
        # follow-up tag? sum up the time
        ended_at="$timestamp"
        diff=$(echo "$ended_at - $started_at" | bc)

        # find the correct index for current_tag
        index=-1
        for i in ${!tag_by_index[@]}
        do
          if [ ${tag_by_index[$i]} == $current_tag ]
          then
            index=$i
          fi
        done

        # update tag-sum storage
        if [ "$index" -eq "-1" ]
        then
          totalled_by_index+=($diff)
          tag_by_index+=($current_tag)
        else
          totalled_by_index[$index]=$(echo "${totalled_by_index[$index]} + $diff" | bc)
        fi

        current_tag="$tag"
        started_at="$timestamp"
      fi
    fi
  else
    echo $(format_date "$(timestamp2date $started_at)")
    for i in "${!tag_by_index[@]}"
    do
      key=${tag_by_index[$i]}
      if [ "$key" != "stop" ]
      then
        duration=$(echo "scale=4; ${totalled_by_index[$i]} / 60.0 / 60.0" | bc)
        echo "${tag_by_index[$i]}:$duration"
      fi
    done
    echo "%%"
    tag_by_index=()
    totalled_by_index=()
  fi
done