#!/bin/bash
# convert the output of a traq file
# <date>;tag
# will become
# <timestamp>;tag

# convert date strings into unix timestamps
function date2timestamp() {
  date -j -f "%a %b %d %T %z %Y" "$1" "+%s"
}

# extract the date string from a traq line
function extractdate() {
  echo "$@" | cut -d';' -f1
}

# extract the tag string from a traq line
function extracttag() {
  echo "$@" | cut -d';' -f2
}

while read LINE
do
  if [ "$LINE" != "%%" ]; then
    printf "$(date2timestamp "$(extractdate "$LINE")");$(extracttag $LINE)\n"
  else
    printf "%%%%\n"
  fi
done