#!/usr/bin/env bash

set +e

. $TRAQ_PATH/traqtrans_helper.sh

TRAQ_CONTENT=""

declare -A totalled
current_tag=""
started_at=""
ended_at=""

while read LINE
do
  if [ "$LINE" != "%%" ]
  then
    # sum up the timestamps
    timestamp=$(extract_date "$LINE")
    tag=$(extract_tag "$LINE")

    if [ "$timestamp" != "" -a "$tag" != "" ]
    then
      # first tag seen? just remember the tag
      if [ "$current_tag" = "" ]
      then
        current_tag="$tag"
        started_at="$timestamp"
        ended_at=""
      else
        # follow-up tag? sum up the time
        ended_at="$timestamp"
        diff=$(echo "$ended_at - $started_at" | bc)

        if [[ ${totalled[$current_tag]} ]]
        then
          totalled[$current_tag]=$(echo "${totalled[$current_tag]} + $diff" | bc)
        else
          totalled[$current_tag]=$diff
        fi

        current_tag="$tag"
        started_at="$timestamp"
      fi
    fi
  else
    echo $(format_date "$(timestamp2date $started_at)")
    for key in "${!totalled[@]}"; do
      if [ "$key" != "stop" ]
      then
        duration=$(echo "scale=4; ${totalled[$key]} / 60.0 / 60.0" | bc)
        echo "$key:$duration"
      fi
    done
    echo "%%"
    totalled=()
  fi
done