#!/bin/bash
# convert the output of a traq file
# <date>;tag
# will become
# <timestamp>;tag

set +e

TRAQ_PATH="$HOME/.traq/"
. $TRAQ_PATH/traq/traqtrans_helper.sh

while read LINE
do
  if [ "$LINE" != "%%" ]
  then
    printf "$(date2timestamp "$(extract_date "$LINE")");$(extract_tag $LINE)\n"
  else
    printf "%%%%\n"
  fi
done